/**
* 
* @author Miguel Maria Vazquez Martinez
* Fifth practice of module PMDM.
* 
*/

package View;

import Controller.ListQuery;
import Model.Employee;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class ListPanel extends javax.swing.JPanel {

    public ListPanel() {
        initComponents();
        model = new DefaultListModel();
        resetMainJList(); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mainJList = new javax.swing.JList<>();
        filterButton = new javax.swing.JButton();
        headerLabelList = new javax.swing.JLabel();
        fromLabelList = new javax.swing.JLabel();
        toLabelList = new javax.swing.JLabel();
        fromDateChooser = new com.toedter.calendar.JDateChooser();
        toDateChooser = new com.toedter.calendar.JDateChooser();
        numberLabelList = new javax.swing.JLabel();
        nameLabelList = new javax.swing.JLabel();
        surnameLabelList = new javax.swing.JLabel();
        salaryLabelList = new javax.swing.JLabel();
        maxSalaryLabelList = new javax.swing.JLabel();
        entryDateLabelList = new javax.swing.JLabel();
        numberFieldList = new javax.swing.JTextField();
        nameFieldList = new javax.swing.JTextField();
        surnameFieldList = new javax.swing.JTextField();
        salaryFieldList = new javax.swing.JTextField();
        maxSalaryFieldList = new javax.swing.JTextField();
        entryDateFieldList = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        clearButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(600, 500));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setPreferredSize(new java.awt.Dimension(600, 500));

        mainJList.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        mainJList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                mainJListValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(mainJList);

        filterButton.setBackground(new java.awt.Color(255, 255, 255));
        filterButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        filterButton.setForeground(new java.awt.Color(0, 0, 0));
        filterButton.setText("Filtrar");
        filterButton.setPreferredSize(new java.awt.Dimension(100, 30));
        filterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterButtonActionPerformed(evt);
            }
        });

        headerLabelList.setBackground(new java.awt.Color(255, 255, 255));
        headerLabelList.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        headerLabelList.setForeground(new java.awt.Color(0, 0, 0));
        headerLabelList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headerLabelList.setText("EMPLEADOS");
        headerLabelList.setMaximumSize(new java.awt.Dimension(200, 30));
        headerLabelList.setMinimumSize(new java.awt.Dimension(200, 30));
        headerLabelList.setPreferredSize(new java.awt.Dimension(200, 30));

        fromLabelList.setBackground(new java.awt.Color(255, 255, 255));
        fromLabelList.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        fromLabelList.setForeground(new java.awt.Color(0, 0, 0));
        fromLabelList.setText("Desde: ");

        toLabelList.setBackground(new java.awt.Color(255, 255, 255));
        toLabelList.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        toLabelList.setForeground(new java.awt.Color(0, 0, 0));
        toLabelList.setText("Hasta:");

        fromDateChooser.setBackground(new java.awt.Color(255, 255, 255));
        fromDateChooser.setForeground(new java.awt.Color(0, 0, 0));
        fromDateChooser.setDateFormatString("dd/MM/yyyy");

        toDateChooser.setBackground(new java.awt.Color(255, 255, 255));
        toDateChooser.setForeground(new java.awt.Color(0, 0, 0));
        toDateChooser.setDateFormatString("dd/MM/yyyy");
        toDateChooser.setMinSelectableDate(fromDateChooser.getDate());
        toDateChooser.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                toDateChooserFocusGained(evt);
            }
        });
        toDateChooser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toDateChooserMouseClicked(evt);
            }
        });

        numberLabelList.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        numberLabelList.setForeground(new java.awt.Color(0, 0, 0));
        numberLabelList.setText("Número:");

        nameLabelList.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        nameLabelList.setForeground(new java.awt.Color(0, 0, 0));
        nameLabelList.setText("Nombre:");

        surnameLabelList.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        surnameLabelList.setForeground(new java.awt.Color(0, 0, 0));
        surnameLabelList.setText("Apellido:");

        salaryLabelList.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        salaryLabelList.setForeground(new java.awt.Color(0, 0, 0));
        salaryLabelList.setText("Salario:");

        maxSalaryLabelList.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        maxSalaryLabelList.setForeground(new java.awt.Color(0, 0, 0));
        maxSalaryLabelList.setText("Salario máximo:");

        entryDateLabelList.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        entryDateLabelList.setForeground(new java.awt.Color(0, 0, 0));
        entryDateLabelList.setText("Fecha de alta:");

        numberFieldList.setEditable(false);
        numberFieldList.setBackground(new java.awt.Color(204, 204, 204));

        nameFieldList.setEditable(false);
        nameFieldList.setBackground(new java.awt.Color(204, 204, 204));

        surnameFieldList.setEditable(false);
        surnameFieldList.setBackground(new java.awt.Color(204, 204, 204));

        salaryFieldList.setEditable(false);
        salaryFieldList.setBackground(new java.awt.Color(204, 204, 204));

        maxSalaryFieldList.setEditable(false);
        maxSalaryFieldList.setBackground(new java.awt.Color(204, 204, 204));

        entryDateFieldList.setEditable(false);
        entryDateFieldList.setBackground(new java.awt.Color(204, 204, 204));

        clearButton.setBackground(new java.awt.Color(255, 255, 255));
        clearButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        clearButton.setForeground(new java.awt.Color(0, 0, 0));
        clearButton.setText("Limpiar");
        clearButton.setPreferredSize(new java.awt.Dimension(100, 30));
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(entryDateLabelList, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(entryDateFieldList, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(numberLabelList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nameLabelList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(surnameLabelList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(salaryLabelList, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maxSalaryLabelList, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(salaryFieldList, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(surnameFieldList, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nameFieldList, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(numberFieldList, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maxSalaryFieldList, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(headerLabelList, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fromLabelList, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toLabelList, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(toDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(filterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fromDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jSeparator1))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(headerLabelList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fromLabelList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(toLabelList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberLabelList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(numberFieldList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameLabelList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameFieldList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(surnameLabelList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(surnameFieldList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salaryLabelList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(salaryFieldList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maxSalaryLabelList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maxSalaryFieldList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(entryDateLabelList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(entryDateFieldList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void toDateChooserFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_toDateChooserFocusGained

    }//GEN-LAST:event_toDateChooserFocusGained

    private void toDateChooserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toDateChooserMouseClicked
        Date date = fromDateChooser.getDate();
        toDateChooser.getJCalendar().setMinSelectableDate(date);
    }//GEN-LAST:event_toDateChooserMouseClicked

    private void filterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButtonActionPerformed
        SimpleDateFormat formatDate = new SimpleDateFormat("yyyy-MM-dd");
        
        if(fromDateChooser.getDate() == null){
            JOptionPane.showMessageDialog(null, "Debe indicar al menos una fecha desde la que filtrar.");
        }else if(toDateChooser.getDate() != null && fromDateChooser.getDate().compareTo(toDateChooser.getDate()) > 0){
            JOptionPane.showMessageDialog(null, "La fecha HASTA no puede ser anterior a DESDE.");
        }else{
            /*
            If the user don't select a date in toDateChooser this option select
            the current date by default.
            */
            if(toDateChooser.getDate() == null){
                toDateChooser.setDate(new Date());
            }
            
            String fromDate = formatDate.format(fromDateChooser.getDate());
            String toDate = formatDate.format(toDateChooser.getDate());
            
            myList = ListQuery.getDBData("SELECT * FROM empleado WHERE fechaalta BETWEEN '"+fromDate+"' AND '"+toDate+"' ORDER BY fechaalta DESC");
            mainJList.setModel(modelList());
        }
        
    }//GEN-LAST:event_filterButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        
        if(fromDateChooser.getDate() == null && toDateChooser.getDate() == null){
            JOptionPane.showMessageDialog(null, "El filtro ya está limpio.");
        }else{
            fromDateChooser.setDate(null);
            toDateChooser.setDate(null);
            clearFieldText();
            resetMainJList();
        }
    }//GEN-LAST:event_clearButtonActionPerformed

    private void mainJListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_mainJListValueChanged

        try{
            if(mainJList.getSelectedValue() != null){
                String[] selected = mainJList.getSelectedValue().split(";");

                numberFieldList.setText(selected[0]);
                nameFieldList.setText(selected[1]);
                surnameFieldList.setText(selected[2]);
                salaryFieldList.setText(selected[3]);
                maxSalaryFieldList.setText(selected[4]);
                entryDateFieldList.setText(selected[5]);
            }
        }catch (Exception ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_mainJListValueChanged

    private void clearFieldText(){
        numberFieldList.setText("");
        nameFieldList.setText("");
        surnameFieldList.setText("");
        salaryFieldList.setText("");
        maxSalaryFieldList.setText("");
        entryDateFieldList.setText("");
    }
    
    public DefaultListModel modelList(){
        
        if(myList == null){
            model.addElement("No existen registros.");
        }else{
            model.removeAllElements();
            
            for(Employee emp : myList){
                model.addElement(emp.toString());
            }
        }
        
        return model;
    }
    
    public void resetMainJList(){
        myList = ListQuery.getDBData("SELECT * FROM empleado ORDER BY numero");
        mainJList.setModel(modelList());
    }
    
    private ArrayList<Employee> myList = new ArrayList();
    private DefaultListModel<String> model;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField entryDateFieldList;
    private javax.swing.JLabel entryDateLabelList;
    private javax.swing.JButton filterButton;
    private com.toedter.calendar.JDateChooser fromDateChooser;
    private javax.swing.JLabel fromLabelList;
    private javax.swing.JLabel headerLabelList;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList<String> mainJList;
    private javax.swing.JTextField maxSalaryFieldList;
    private javax.swing.JLabel maxSalaryLabelList;
    private javax.swing.JTextField nameFieldList;
    private javax.swing.JLabel nameLabelList;
    private javax.swing.JTextField numberFieldList;
    private javax.swing.JLabel numberLabelList;
    private javax.swing.JTextField salaryFieldList;
    private javax.swing.JLabel salaryLabelList;
    private javax.swing.JTextField surnameFieldList;
    private javax.swing.JLabel surnameLabelList;
    private com.toedter.calendar.JDateChooser toDateChooser;
    private javax.swing.JLabel toLabelList;
    // End of variables declaration//GEN-END:variables
}
